### ISSUE TITLE
[Structure] 컴포넌트 관련

### ISSUE THREAD

**Issue by parkgeonhu** [KMU-WINK/hssp-web#12]
리액트 컴포넌트 활용할 때, 특정 페이지에만 활용되는 컴포넌트, 공통적으로 사용하는 컴포넌트들이 있더라고요.

그래서 그런데 components 폴더 안에,

* 공통적으로 사용되는 컴포넌트의 경우 ` common ` 이라는 폴더 안에
* PX 페이지에서만 사용되는 컴포넌트는 ` px ` 라는 폴더 안에

넣는 것은 어떤가 싶어서 제안합니다. 그 외의 의견 있으시면 말씀해주세용

**Comment by parkgeonhu** [comment]
아니면 Card 관련 컴포넌트들을 모아서 정리해보는 것도 괜찮겠네요. cards라는 폴더를 만들어서

**Comment by bell2lee** [comment]
찬성입니다. 페이지가 어느정도 나오면 진행하려 했던 부분이나 현재 진행해도 좋을 것 같습니다.
해당 부분 수정해서 풀리퀘 올립니다.

추가로 메인페이지 부분에 카드 컴포넌트 구조를 조금 변경해야할 것 같습니다. 이 부분은 추후 작업하겠습니다.

**Comment by parkgeonhu** [comment]
@bell2lee 확인했고, merge 하셔도 좋을 듯합니다!
