### ISSUE TITLE
회원가입 페이지

### ISSUE THREAD

**Issue by bell2lee** [KMU-WINK/hssp-web#3]
- 입력 폼
- 체크박스

**Comment by wwjdtm** [comment]
버튼 컴포넌트를 만들어서 추가했는데 , 왜 page-signup.js에는 버튼 하나만 적용이될까요..
회원가입버튼도 추가하고싶은데, 추가하면 자꾸 로그인버튼이름만 바껴요..흑ㅎㄱ륵ㄱ
